# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f0f0f7cb-cf77-4aec-9c4a-a233cf3ecbd5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f0f0f7cb-cf77-4aec-9c4a-a233cf3ecbd5".device = "/dev/disk/by-uuid/f0f0f7cb-cf77-4aec-9c4a-a233cf3ecbd5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C459-B42F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
